CSP_CREW_HOMEPAGE/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('csp_on/', admin.site.urls),
    path('main/', include('csp_main_home.urls')),
    path('', include('csp_main_home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # board
    path('hackboard/', include('csp_hack_board.urls')),
    path('progboard/', include('csp_prog_board.urls')),
    path('ctfboard/', include('csp_ctf_board.urls')),
    path('aboutboard/', include('csp_about_board.urls')),

    # account
    path('sign_c/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('sign/', views.sign, name='sign'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('user/', views.user, name='user'),
    path('delete/', views.delete, name='delete'),
    path('change_password/', views.change_password, name='change_password'),

    url(r'^nop/$', views.Nop.as_view(), name='nop'),
]

csp_hack_board/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'csp_hack_board'

urlpatterns = [
    url(r'^$', views.Csp_hack_board.as_view(), name='csp_hack_board'),
    url(r'^insert/$', views.check_post, name='csp_hack_insert'),
    path('<int:pk>/detail/', views.csp_hack_detail, name='csp_hack_detail'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.Csp_hack_update.as_view(), name='csp_hack_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.Csp_hack_delete.as_view(), name='csp_hack_delete'),
    url(r'^nop/$', views.Nop.as_view(), name='nop'),

    #qna
    url(r'^qna/$', views.Csp_hack_board_qna.as_view(), name='csp_hack_board_qna'),
    url(r'^qna/insert/$', views.check_post_qna, name='csp_hack_insert_qna'),
    path('qna/<int:pk>/detail/', views.csp_hack_detail_qna, name='csp_hack_detail_qna'),
    url(r'^qna/(?P<pk>[0-9]+)/update/$', views.Csp_hack_update_qna.as_view(), name='csp_hack_update_qna'),
    url(r'^qna/(?P<pk>[0-9]+)/delete/$', views.Csp_hack_delete_qna.as_view(), name='csp_hack_delete_qna'),

    #comment
    path('<int:pk>/detail/comment/delete/<int:comment_id>/', views.comment_delete, name="comment_delete"),
    path('comment/update/<int:comment_id>/', views.comment_update, name="comment_update"),
    path('qna/<int:pk>/detail/comment/delete/<int:comment_id>/', views.comment_delete_qna, name="comment_delete_qna"),
    path('qna/comment/update/<int:comment_id>/', views.comment_update_qna, name="comment_update_qna"),

    #action
    path('close/', views.closed_page, name="closed_page")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csp_hack_board/models.py
from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class ProjectCode(models.Model):
    pcode = models.CharField(primary_key=True, max_length=4)
    pname = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'project_code'

class Csp_hack_list(models.Model):
    no = models.AutoField(primary_key=True)
    pcode = models.CharField(max_length=4)
    user_id = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    content = RichTextUploadingField(max_length=20000)
    is_complete = models.BooleanField()
    end_date = models.DateTimeField(default=timezone.now())
    user_name = models.CharField(max_length=50)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def csp_hack_save(self):
        self.save()

    class Meta:
        managed = False
        db_table = 'hack_board'


class Hack_comment(models.Model):
    no = models.ForeignKey(Csp_hack_list, on_delete=models.CASCADE, related_name='comments')
    user_no = models.AutoField(primary_key=True)
    comment = models.TextField(max_length=1000)
    insert_date = models.DateTimeField(default=timezone.now())
    user_name = models.CharField(max_length=50)
    user_id = models.CharField(max_length=150)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def csp_hack_save(self):
        self.save()

    class Meta:
        managed = False
        db_table = 'hack_comment'


class Csp_hack_list_qna(models.Model):
    no = models.AutoField(primary_key=True)
    pcode = models.CharField(max_length=4)
    user_id = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    content = RichTextUploadingField(max_length=20000)
    is_complete = models.BooleanField()
    end_date = models.DateTimeField(default=timezone.now())
    user_name = models.CharField(max_length=50)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def csp_hack_save_qna(self):
        self.save()

    class Meta:
        managed = False
        db_table = 'hack_board_qna'

class Hack_comment_qna(models.Model):
    no = models.ForeignKey(Csp_hack_list_qna, on_delete=models.CASCADE, related_name='comments')
    user_no = models.AutoField(primary_key=True)
    comment = models.TextField(max_length=1000)
    insert_date = models.DateTimeField(default=timezone.now())
    user_name = models.CharField(max_length=50)
    user_id = models.CharField(max_length=150)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def csp_hack_save(self):
        self.save()

    class Meta:
        managed = False
        db_table = 'hack_comment_qna'

csp_hack_board/forms.py
from django import forms
from .models import Csp_hack_list, Csp_hack_list_qna, Hack_comment, Hack_comment_qna
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class Csp_hack_form(forms.ModelForm):
    class Meta:
        model = Csp_hack_list
        fields = ('title', 'content', 'is_complete')

    widgets = {
        'content': forms.CharField(widget=CKEditorUploadingWidget()),
    }

class Hack_CommentForm(forms.ModelForm):

    class Meta:
        model = Hack_comment
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['comment'].label = "댓글"

class Csp_hack_form_qna(forms.ModelForm):
    class Meta:
        model = Csp_hack_list_qna
        fields = ('title', 'content', 'is_complete')

    widgets = {
        'content': forms.CharField(widget=CKEditorUploadingWidget()),
    }

class Hack_CommentForm_qna(forms.ModelForm):

    class Meta:
        model = Hack_comment_qna
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['comment'].label = "댓글"

csp_hack_board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Csp_hack_list, Csp_hack_list_qna, Hack_comment, Hack_comment_qna
from .forms import Csp_hack_form, Csp_hack_form_qna, Hack_CommentForm, Hack_CommentForm_qna

# Create your views here.

from django.views import generic
from django.core.paginator import Paginator


class Csp_hack_board(generic.TemplateView):

    def get(self, request, *args, **kwargs):

        if request.user.is_authenticated == False:
            return render(self.request, 'nop.html', {"message": "Nop! Login First."})

        elif request.user.last_name != 'hack' and request.user.last_name != 'admin':
            return render(self.request, 'nop.html', {"message": "Nop! You are not hacking member!"})

        template_name = 'hack_board.html'
        csp_hack_page = Csp_hack_list.objects
        hack_page_list = Csp_hack_list.objects.all().order_by('-no')
        paginator = Paginator(hack_page_list, 10)
        page = request.GET.get('page')
        posts = paginator.get_page(page)

        return render(request, template_name, {'csp_hack_page': csp_hack_page, 'posts': posts, 'top': hack_page_list})

def csp_hack_detail(request, pk):
    question = get_object_or_404(Csp_hack_list, pk=pk)

    if request.method == "POST":
        comment_form = Hack_CommentForm(request.POST)
        comment_form.instance.user_name = request.user.first_name
        comment_form.instance.no_id = pk
        comment_form.instance.user_id = request.user.username
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.csp_hack_save()

    comment_form = Hack_CommentForm()
    comments = question.comments.all()

    return render(request, 'csp_hack_detail.html',
                  {'csp_hack_list': question, "comments": comments, "comment_form": comment_form})

class Csp_hack_update(generic.UpdateView):

    def get(self, request, *args, **kwargs):

        if request.user.is_authenticated == False:
            return render(self.request, 'nop.html', {"message": "Nop! Login First."})

        elif request.user.last_name != 'hack' and request.user.last_name != 'admin':
            return render(self.request, 'nop.html', {"message": "Nop! You are not hacking member!"})

    model = Csp_hack_list
    fields = ('title', 'content', 'is_complete')
    template_name = 'csp_hack_update.html'
    success_url = '/hackboard/'

    def form_valid(self, form):
        form.save()
        return render(self.request, 'csp_hack_success.html', {"message": "Update Success!"})

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

class Csp_hack_delete(generic.DeleteView):
    model = Csp_hack_list
    success_url = '/hackboard/'
    context_object_name = 'csp_hack_list'

class Nop(generic.TemplateView):

    def check_post(self, request):

        template_name = 'nop.html'
        message = "Nop! Login First."

        return render(request, template_name, {"message":message})

def check_post(request):

    template_name = 'csp_hack_success.html'

    if request.method == "POST":
        form = Csp_hack_form(request.POST)
        if form.is_valid():
            hack = form.save(commit=False)
            hack.user_id = request.user.first_name
            hack.user_name = request.user.username
            hack.csp_hack_save()
            message = "Success!"
            return render(request, template_name, {"message":message})

    else:
        template_name = 'csp_hack_insert.html'
        form = Csp_hack_form
        return render(request, template_name, {"form" : form})

    # QNA ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # QNA ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

class Csp_hack_board_qna(generic.TemplateView):

    def get(self, request, *args, **kwargs):

        if request.user.is_authenticated == False:
            return render(self.request, 'nop.html', {"message": "Nop! Login First."})

        elif request.user.last_name != 'hack' and request.user.last_name != 'admin':
            return render(self.request, 'nop.html', {"message": "Nop! You are not hacking member!"})

        template_name = 'hack_board_qna.html'
        csp_hack_qna = Csp_hack_list_qna.objects
        hack_page_qna = Csp_hack_list_qna.objects.all().order_by('-no')
        paginator = Paginator(hack_page_qna, 10)
        page = request.GET.get('page')
        posts = paginator.get_page(page)

        return render(request, template_name, {'csp_hack_qna': csp_hack_qna, 'posts': posts, 'top': hack_page_qna})

def csp_hack_detail_qna(request, pk):
    question = get_object_or_404(Csp_hack_list_qna, pk=pk)

    if request.method == "POST":
        comment_form = Hack_CommentForm_qna(request.POST)
        comment_form.instance.user_name = request.user.first_name
        comment_form.instance.no_id = pk
        comment_form.instance.user_id = request.user.username
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.csp_hack_save()

    comment_form = Hack_CommentForm_qna()
    comments = question.comments.all()

    return render(request, 'csp_hack_detail_qna.html',
                  {'csp_hack_list_qna': question, "comments": comments, "comment_form": comment_form})

class Csp_hack_update_qna(generic.UpdateView):

    def get(self, request, *args, **kwargs):

        if request.user.is_authenticated == False:
            return render(self.request, 'nop.html', {"message": "Nop! Login First."})

        elif request.user.last_name != 'hack' and request.user.last_name != 'admin':
            return render(self.request, 'nop.html', {"message": "Nop! You are not hacking member!"})

    model = Csp_hack_list_qna
    fields = ('title', 'content', 'is_complete')
    template_name = 'csp_hack_update_qna.html'
    success_url = '/hackboard/qna/'

    def form_valid(self, form):
        form.save()
        return render(self.request, 'csp_hack_success_qna.html', {"message": "Update Success!"})

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

class Csp_hack_delete_qna(generic.DeleteView):
    model = Csp_hack_list_qna
    success_url = '/hackboard/qna/'
    context_object_name = 'csp_hack_list_qna'

def check_post_qna(request):

    template_name = 'csp_hack_success_qna.html'

    if request.method == "POST":
        form = Csp_hack_form_qna(request.POST)
        if form.is_valid():
            hack = form.save(commit=False)
            hack.user_id = request.user.first_name
            hack.user_name = request.user.username
            hack.csp_hack_save_qna()
            message = "Success!"
            return render(request, template_name, {"message":message})

    else:
        template_name = 'csp_hack_insert_qna.html'
        form = Csp_hack_form_qna
        return render(request, template_name, {"form" : form})

def comment_update(request, comment_id):
    comment = get_object_or_404(Hack_comment, pk=comment_id)

    if request.user.is_authenticated == False:
        return render(request, 'nop.html', {"message": "Nop! Login First."})

    elif request.user.last_name != 'hack' and request.user.last_name != 'admin':
        return render(request, 'nop.html', {"message": "Nop! You are not hacking member!"})

    if request.method == "POST":
        form = Hack_CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('/hackboard/close/')
    else:
        form = Hack_CommentForm(instance=comment)
    return render(request,'hack_comment_update.html', {'form':form, 'hack_comment':comment})

def comment_delete(request, pk, comment_id):
    comment = get_object_or_404(Hack_comment, pk=comment_id)

    if request.user.is_authenticated == False:
        return render(request, 'nop.html', {"message": "Nop! Login First."})

    elif request.user.last_name != 'hack' and request.user.last_name != 'admin':
        return render(request, 'nop.html', {"message": "Nop! You are not hacking member!"})

    if request.method == "POST":
        comment.delete()
        return redirect('/hackboard/' + str(pk) + '/detail/')
    else:
        return render(request, 'hack_comment_delete.html', {'object':comment})

def closed_page(request):
    template_name = 'closed_page.html'
    return render(request, template_name)

def comment_update_qna(request, comment_id):
    comment = get_object_or_404(Hack_comment_qna, pk=comment_id)

    if request.user.is_authenticated == False:
        return render(request, 'nop.html', {"message": "Nop! Login First."})

    elif request.user.last_name != 'hack' and request.user.last_name != 'admin':
        return render(request, 'nop.html', {"message": "Nop! You are not hacking member!"})

    if request.method == "POST":
        form = Hack_CommentForm_qna(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('/hackboard/close/')
    else:
        form = Hack_CommentForm(instance=comment)
    return render(request,'hack_comment_update.html', {'form':form, 'hack_comment':comment})

def comment_delete_qna(request, pk, comment_id):
    comment = get_object_or_404(Hack_comment_qna, pk=comment_id)

    if request.user.is_authenticated == False:
        return render(request, 'nop.html', {"message": "Nop! Login First."})

    elif request.user.last_name != 'hack' and request.user.last_name != 'admin':
        return render(request, 'nop.html', {"message": "Nop! You are not hacking member!"})

csp_hack_board/templates/closed_page.html
<script language="javascript">
    self.close();
</script>

csp_hack_board/templates/csp_hack_detail.html
<meta charset="utf-8">

{% load static %}

<html>
    <head>

        <title>
            해킹 동아리 게시판 글
        </title>
        
        <link rel="stylesheet" type="text/css" href="{% static 'css/btn.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/btn_hover_board.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/backstyle.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/hack_board_title.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/wrapper.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/notice.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/board.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/comment.css' %}">

    <input type="checkbox" id="top_icon">
        <label for="top_icon">
            <span></span>
            <span></span>
            <span></span>
        </label>
    <div class="top_bar">
    <ul class = "menu">
        <li class="logo_li"><a href = "/main"><img src = "{% static 'img/mainlogo_.png' %}" alt = "main_logo" width = "50" class = "logo"></a></li>
        <div class="add_margin">
        <li><a href="/main/">Home</a></li>
        <li><a href="/aboutboard">About</a></li>
        <li><a href="/ctfboard">CTF schedule</a></li>
        <li><a class="active" href="/hackboard">Hacking</a></li>
        <li><a href="/progboard">Programming</a></li>
        <li class="log">
            {% if user.is_authenticated %}
            <a href="/sign_c/user">{{ user.first_name }}님, 안녕하세요.</a>
        </li>
        <li class="inout">
            <a href="/sign_c/logout">Logout</a>
        </li>
        <li class="log">
            {% else %}
            <a href="/sign_c/login">Login</a>
        </li>
        <li class="inout">
            <a href="/sign_c/sign">Sign up</a>
            {% endif %}
        </li>
        </div>
    </ul><br></div>

    </head>
{% block main %}
    <body>

        {% if user.last_name != 'hack' and user.last_name != 'admin' %}
        <script>
            window.location.replace('/main')
            alert('Nop! You are not hacking member!')
        </script>
        {% endif %}

        <div class="board_margin">

            <section>
                <div class="grp-text">
                    <div class="back-g-i">
                    <h2 class="board-detail-title">
                        {{ csp_hack_list.title }}
                    </h2>
                    <h4 class="board-detail-user">작성자 : {{ csp_hack_list.user_id }}</h4>
                    <h4 class="board-detail-time">{{ csp_hack_list.end_date }}</h4><hr>
                    </div>
                    <div class="back-g-a">

                    <div class="detail-text-box"><p>{{ csp_hack_list.content | safe }}</p><br></div>
                        {% if csp_hack_list.user_name == user.username %}
                    <h2 class="detail-btn">
                        <a href="{% url 'csp_hack_board:csp_hack_update' pk=csp_hack_list.pk %}">
                        <img width="50px" src="{% static 'img/insert.png' %}">
                        </a>

                        <a href="{% url 'csp_hack_board:csp_hack_delete' pk=csp_hack_list.pk %}">
                            <img width="50px" src="{% static 'img/dee.png' %}">
                        </a>
                    </h2>
                        {% endif %}
                    </div>

                    <form method="POST" class="comment_input">
                    {% csrf_token %}
                        <input type="text" name="comment" maxlength="1000">
                        <input type="submit" value="Comment">

                    </form>
                    <hr>
                    <table>
                        {% for comment in comments %}
                        <tr>
                            <td class="comment_text">{{ comment.comment }}</td>
                            <td class="comment_name">{{ comment.user_name }}</td>
                            <td class="comment_date">{{ comment.insert_date }}</td>
                            {% if comment.user_id == user.username %}
                            <td class="comment_btn"><input type="submit" value="삭제" onclick="location.href = 'comment/delete/{{ comment.user_no }}'"></td>
                            <td class="comment_btn"><input type="submit" value="수정" onclick="window.open('/hackboard/comment/update/{{ comment.user_no }}','댓글 수정','width=320,height=230,location=no,status=no,scrollbars=yes');"></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </table>
                    <hr>
                    <button type="submit" value="BACK" onclick = "location.href = '/hackboard'" style="width : 100%;">
                        BACK
                    </button>
                    <div class="back-g-b"></div>
                </div>
            </section>

        </div>

    </body>
{% endblock main %}
</html>

csp_hack_board/templates/csp_hack_detail_qna.html
<meta charset="utf-8">

{% load static %}

<html>
    <head>

        <title>
            해킹 동아리 게시판 QnA
        </title>
        
        <link rel="stylesheet" type="text/css" href="{% static 'css/btn.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/btn_hover_board.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/backstyle.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/hack_board_title.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/wrapper.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/notice.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/board.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/comment.css' %}">

    <input type="checkbox" id="top_icon">
        <label for="top_icon">
            <span></span>
            <span></span>
            <span></span>
        </label>
    <div class="top_bar">
    <ul class = "menu">
        <li class="logo_li"><a href = "/main"><img src = "{% static 'img/mainlogo_.png' %}" alt = "main_logo" width = "50" class = "logo"></a></li>
        <div class="add_margin">
        <li><a href="/main/">Home</a></li>
        <li><a href="/aboutboard">About</a></li>
        <li><a href="/ctfboard">CTF schedule</a></li>
        <li><a class="active" href="/hackboard">Hacking</a></li>
        <li><a href="/progboard">Programming</a></li>
        <li class="log">
            {% if user.is_authenticated %}
            <a href="/sign_c/user">{{ user.first_name }}님, 안녕하세요.</a>
        </li>
        <li class="inout">
            <a href="/sign_c/logout">Logout</a>
        </li>
        <li class="log">
            {% else %}
            <a href="/sign_c/login">Login</a>
        </li>
        <li class="inout">
            <a href="/sign_c/sign">Sign up</a>
            {% endif %}
        </li>
        </div>
    </ul><br></div>

    </head>
{% block main %}
    <body>

        {% if user.last_name != 'hack' and user.last_name != 'admin' %}
        <script>
            window.location.replace('/main')
            alert('Nop! You are not hacking member!')
        </script>
        {% endif %}

        <div class="board_margin">

            <section>
                <div class="grp-text">
                    <div class="back-g-i">
                    <h2 class="board-detail-title">
                        {{ csp_hack_list_qna.title }}
                    </h2>
                    <h4 class="board-detail-user">작성자 : {{ csp_hack_list_qna.user_id }}</h4>
                    <h4 class="board-detail-time">{{ csp_hack_list_qna.end_date }}</h4><hr>
                    </div>
                    <div class="back-g-a">

                    <div class="detail-text-box"><p>{{ csp_hack_list_qna.content | safe }}</p><br></div>
                        {% if csp_hack_list_qna.user_name == user.username %}
                    <h2 class="detail-btn">
                        <a href="{% url 'csp_hack_board:csp_hack_update_qna' pk=csp_hack_list_qna.pk %}">
                            <img width="50px" src="{% static 'img/insert.png' %}">
                        </a>

                        <a href="{% url 'csp_hack_board:csp_hack_delete_qna' pk=csp_hack_list_qna.pk %}">
                            <img width="50px" src="{% static 'img/dee.png' %}">
                        </a>
                    </h2>
                        {% endif %}
                    </div>
                    <form method="POST" class="comment_input">
                    {% csrf_token %}
                        <input type="text" name="comment" maxlength="1000">
                        <input type="submit" value="Comment">

                    </form>
                    <hr>
                    <table>
                        {% for comment in comments %}
                        <tr>
                            <td class="comment_text">{{ comment.comment }}</td>
                            <td class="comment_name">{{ comment.user_name }}</td>
                            <td class="comment_date">{{ comment.insert_date }}</td>
                            {% if comment.user_id == user.username %}
                            <td class="comment_btn"><input type="submit" value="삭제" onclick="location.href = 'comment/delete/{{ comment.user_no }}'"></td>
                            <td class="comment_btn"><input type="submit" value="수정" onclick="window.open('/hackboard/qna/comment/update/{{ comment.user_no }}','댓글 수정','width=320,height=230,location=no,status=no,scrollbars=yes');"></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </table>
                    <hr>
                    <button type="submit" value="BACK" onclick = "location.href = '/hackboard/qna/' " style="width : 100%;">
                        BACK
                    </button>
                    <div class="back-g-b"></div>
                </div>
            </section>

        </div>

    </body>
{% endblock main %}
</html>

csp_hack_board/templates/csp_hack_success.html
<script>
    message = "{{ message }}";
    console.log(message);
    alert(message);
    location.href = '/hackboard/';
</script>

csp_hack_board/templates/csp_hack_success_qna.html
<script>
    message = "{{ message }}";
    console.log(message);
    alert(message);
    location.href = '/hackboard/qna';
</script>

csp_hack_board/templates/hack_comment_update.html
<meta charset="utf-8">

{% load static %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/btn.css' %}">
    </head>

    <body style="background-color:rgba(30, 22, 54, 0.9);">
        {% block content %}

        {% if user.last_name != 'hack' and user.last_name != 'admin' %}
        <script>
            window.location.replace('/main')
            alert('Nop! You are not hacking member!')
        </script>
        {% elif user.username != hack_comment.user_id %}
        <script>
            self.close();
            alert('Nop!')
        </script>
        {% endif %}

        <form action="" method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form.comment }}
            </table>
            <button type="submit" value="Write" style="width : 100%;">Update</button>

        </form>

        {% endblock %}
    </body>
</html>

csp_hack_board/templates/nop.html
<script>
    message = "{{ message }}";
    console.log(message);
    alert(message);
    location.href = '/sign_c/login/';
</script>